import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Base64
import java.util.Properties
import kotlin.math.sqrt

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.plugin.compose")
}

fun readLocalPropertyOrNull(key: String): String? {
    val localPropsFile = rootProject.file("local.properties")
    if (!localPropsFile.exists()) return null
    return runCatching {
        val props = Properties()
        localPropsFile.inputStream().use(props::load)
        props.getProperty(key)
    }.getOrNull()
}

abstract class BakeAppSquircleSdfTask : DefaultTask() {
    @get:Input
    abstract val control: Property<Float>

    @get:Input
    abstract val size: Property<Int>

    @get:Input
    abstract val halfRange: Property<Float>

    @get:Input
    abstract val bezierSamples: Property<Int>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun bake() {
        val resolvedSize = size.get()
        val resolvedControl = control.get()
        val resolvedHalfRange = halfRange.get()
        val resolvedBezierSamples = bezierSamples.get()
        val resolvedPackage = packageName.get()
        val bytes =
            generateSdfBytes(
                size = resolvedSize,
                control = resolvedControl,
                halfRange = resolvedHalfRange,
                bezierSamples = resolvedBezierSamples,
            )
        val chunks = Base64.getEncoder().encodeToString(bytes).chunked(60_000)
        val packageDir = outputDir.get().asFile.resolve(resolvedPackage.replace('.', '/'))
        packageDir.mkdirs()
        packageDir.resolve("BakedAppSquircleSdf.kt").writeText(
            buildString {
                appendLine("// Auto-generated by :ui-liquid-glass:bakeAppSquircleSdf.")
                appendLine("@file:Suppress(\"PropertyName\")")
                appendLine()
                appendLine("package $resolvedPackage")
                appendLine()
                appendLine("import java.util.Base64")
                appendLine()
                appendLine("internal object BakedAppSquircleSdf {")
                appendLine("    const val CONTROL: Float = ${resolvedControl}f")
                appendLine("    const val SIZE: Int = $resolvedSize")
                appendLine("    const val HALF_RANGE: Float = ${resolvedHalfRange}f")
                appendLine("    private val CHUNKS: Array<String> = arrayOf(")
                chunks.forEach { chunk ->
                    appendLine("        \"$chunk\",")
                }
                appendLine("    )")
                appendLine("    val bytes: ByteArray by lazy(LazyThreadSafetyMode.PUBLICATION) {")
                appendLine("        Base64.getDecoder().decode(CHUNKS.joinToString(\"\"))")
                appendLine("    }")
                appendLine("}")
            },
        )
    }

    private fun generateSdfBytes(
        size: Int,
        control: Float,
        halfRange: Float,
        bezierSamples: Int,
    ): ByteArray {
        val handle = 1f - control
        val bx = FloatArray(bezierSamples + 1)
        val by = FloatArray(bezierSamples + 1)
        for (index in 0..bezierSamples) {
            val t = index.toFloat() / bezierSamples
            val omt = 1f - t
            bx[index] = 3f * omt * t * t * handle + t * t * t
            by[index] = omt * omt * omt + 3f * omt * omt * t * handle
        }
        val bytes = ByteArray(size * size)
        val invSize = 1f / size
        val invRange2 = 1f / (2f * halfRange)
        for (py in 0 until size) {
            val y = (py + 0.5f) * invSize
            for (px in 0 until size) {
                val x = (px + 0.5f) * invSize
                var minSqDist = Float.MAX_VALUE
                var closestIndex = 0
                for (index in 0 until bezierSamples) {
                    val ax = bx[index]
                    val ay = by[index]
                    val sx = bx[index + 1] - ax
                    val sy = by[index + 1] - ay
                    val len2 = sx * sx + sy * sy
                    if (len2 < 1e-12f) continue
                    val u = (((x - ax) * sx + (y - ay) * sy) / len2).coerceIn(0f, 1f)
                    val qx = ax + u * sx
                    val qy = ay + u * sy
                    val ddx = x - qx
                    val ddy = y - qy
                    val sqDist = ddx * ddx + ddy * ddy
                    if (sqDist < minSqDist) {
                        minSqDist = sqDist
                        closestIndex = index
                    }
                }
                val dist = sqrt(minSqDist)
                val tx = bx[closestIndex + 1] - bx[closestIndex]
                val ty = by[closestIndex + 1] - by[closestIndex]
                val pdx = x - bx[closestIndex]
                val pdy = y - by[closestIndex]
                val cross = tx * pdy - ty * pdx
                val signedDist = if (cross > 0f) -dist else dist
                val alpha = (0.5f - signedDist * invRange2).coerceIn(0f, 1f)
                bytes[py * size + px] = (alpha * 255f + 0.5f).toInt().toByte()
            }
        }
        return bytes
    }
}

val miuixVersion =
    providers.gradleProperty("miuix.version").orNull
        ?: readLocalPropertyOrNull("miuix.version")
        ?: "0.9.1"
val composeVersion = "1.11.2"
val activityComposeVersion = "1.13.0"
val backdropVersion = "2.0.0"
val capsuleVersion = "2.1.3"
val shapesVersion = "1.2.0"
val lucideIconsVersion = "2.2.1"
val projectCompileSdk = 37
val projectMinSdk = 35
val projectJavaVersion = JavaVersion.VERSION_21
val projectJvmTarget = JvmTarget.JVM_21

val bakeAppSquircleSdf by tasks.registering(BakeAppSquircleSdfTask::class) {
    description = "Bake KeiOS AppSquircle SDF bytes into generated source."
    control.set(0.63f)
    size.set(256)
    halfRange.set(0.125f)
    bezierSamples.set(64)
    packageName.set("os.kei.ui.page.main.widget.shape.internal")
    outputDir.set(layout.buildDirectory.dir("generated/app-squircle-sdf"))
}

android {
    namespace = "os.kei.ui.liquidglass"
    compileSdk = projectCompileSdk

    defaultConfig {
        minSdk = projectMinSdk
    }

    compileOptions {
        sourceCompatibility = projectJavaVersion
        targetCompatibility = projectJavaVersion
    }

    buildFeatures {
        compose = true
    }

    lint {
        abortOnError = true
        checkDependencies = false
    }

    compileSdkMinor = 0

    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
}

androidComponents {
    onVariants { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(
            bakeAppSquircleSdf,
            BakeAppSquircleSdfTask::outputDir,
        )
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(projectJvmTarget)
    }
}

configurations.configureEach {
    resolutionStrategy.dependencySubstitution {
        substitute(module("top.yukonga.miuix.kmp:miuix-ui"))
            .using(module("top.yukonga.miuix.kmp:miuix-ui-android:$miuixVersion"))
        substitute(module("top.yukonga.miuix.kmp:miuix-icons"))
            .using(module("top.yukonga.miuix.kmp:miuix-icons-android:$miuixVersion"))
        substitute(module("top.yukonga.miuix.kmp:miuix-blur"))
            .using(module("top.yukonga.miuix.kmp:miuix-blur-android:$miuixVersion"))
    }
}

dependencies {
    api("androidx.activity:activity-compose:$activityComposeVersion")
    api("androidx.compose.ui:ui:$composeVersion")
    api("androidx.compose.foundation:foundation:$composeVersion")
    api("androidx.compose.ui:ui-tooling-preview:$composeVersion")
    api("top.yukonga.miuix.kmp:miuix-ui-android:$miuixVersion")
    api("top.yukonga.miuix.kmp:miuix-icons-android:$miuixVersion")
    api("top.yukonga.miuix.kmp:miuix-blur-android:$miuixVersion")
    api("io.github.kyant0:backdrop:$backdropVersion")
    api("io.github.kyant0:capsule:$capsuleVersion")
    api("io.github.kyant0:shapes:$shapesVersion")
    api("com.composables:icons-lucide-android:$lucideIconsVersion")

    testImplementation(kotlin("test"))
    testImplementation("junit:junit:4.13.2")
    testImplementation("androidx.compose.ui:ui-test-junit4:$composeVersion")
    testImplementation("androidx.test.ext:junit:1.3.0")
    testImplementation("org.robolectric:robolectric:4.16.1")
    debugImplementation("androidx.compose.ui:ui-test-manifest:$composeVersion")
}
