package os.kei.ui.page.main.widget.markdown

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class AppMarkdownParserTest {
    @Test
    fun releaseNotesBodyParsesIntoStructuredBlocks() {
        val blocks = parseAppMarkdownBlocks(
            """
                <!-- generated by github -->
                # Release Notes

                ## What's Changed
                - Added **installer** flow
                1. Fixed `cache` refresh

                ```kotlin
                val version = "1.0"
                ```
            """.trimIndent()
        )

        assertEquals(AppMarkdownBlock.Heading(1, "Release Notes"), blocks[0])
        assertEquals(AppMarkdownBlock.Heading(2, "What's Changed"), blocks[1])
        assertEquals(AppMarkdownBlock.Bullet("Added **installer** flow"), blocks[2])
        assertEquals(AppMarkdownBlock.Ordered(1, "Fixed `cache` refresh"), blocks[3])
        assertEquals(AppMarkdownBlock.Code("val version = \"1.0\""), blocks[4])
    }

    @Test
    fun inlineTokensKeepReleaseNoteEmphasisCodeAndLinks() {
        val tokens = parseAppMarkdownInlineTokens(
            "Added **install** and `cache`; see [release](https://github.com/demo/app/releases)"
        )

        assertTrue(tokens.any { it == AppMarkdownInlineToken.Emphasis("install") })
        assertTrue(tokens.any { it == AppMarkdownInlineToken.Code("cache") })
        assertTrue(
            tokens.any {
                it == AppMarkdownInlineToken.Link(
                    label = "release",
                    url = "https://github.com/demo/app/releases"
                )
            }
        )
    }
}
